trigger:
-  ⁠master

pool:
  name: Default

steps:
- ⁠script: echo my azure
  displayName: 'Run a one-line script'

-⁠ ⁠script: gradle build
  displayName: 'Building the gradle application'

-⁠ ⁠script: gradle run
  displayName: 'Running gradle application'